---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfseceng/credhub

inputs:
- name: alpha-rotato

run:
  path: alpha-rotato/tasks/rotate-credentials.sh

params:
  CREDHUB_SERVER:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_CA_CERT:
  CREDS_TO_ROTATE:

