---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfseceng/credhub

inputs:
- name: alpha-rotato

run:
  path: alpha-rotato/tasks/rotate-certificates-by-ca.sh

params:
  CREDHUB_SERVER:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_CA_CERT:
  SIGNED_BY_TO_ROTATE:
  BOSH_NAME:
  BOSH_DEPLOYMENT:

