resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources: 
# - name: alpha-rotato
#   type: git
#   source:
#     uri: https://github.com/danjahner/alpha-rotato.git
#     branch: master

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    tag_filter: v0.30.0

- name: deploy-cf
  type: bosh-deployment
  source:
    deployment: cf
    target: ((director-addr))
    client: ((dan_director_client.username))
    client_secret: ((dan_director_client.password))
    ca_cert: ((dan_director_gcp_ca.certificate))

jobs: 
- name: deploy-cf
  plan: 
  - get: cf-deployment
  - put: deploy-cf
    params:
      manifest: cf-deployment/cf-deployment.yml
      vars: 
        system_domain: diego.security.cf-app.com
