# This pipeline provides the ability to manually trigger rotation of certain credentials in cf-deployment.
#
# Variables Needed--
#  director_addr        : The address of your cf-deployment bosh director
#  director_client      : Client credentials used to authenticate with the bosh director and CredHub. Must be stored as a user type.
#  director_ca          : The CA to trust when connecting to the bosh director
#  director_name        : The name of your bosh director
#  deployment_name      : The name of your cf-deployment
#  director_jumpbox     : SSH private key for jumpbox to allow bosh SSH

properties: 
  deploy_config: &deploy_config 
    BOSH_ENVIRONMENT: ((director_addr))
    BOSH_DEPLOYMENT: ((deployment_name))
    BOSH_CA_CERT: ((director_ca.certificate))
    BOSH_CLIENT: ((director_client.username))
    BOSH_CLIENT_SECRET: ((director_client.password))

groups: 
- name: basic-credentials
  jobs: 
  - manual-rotate-basics
  - rotate-certificates
  - rotate-uaa-client-secrets
  - rotate-nats-password
  - rotate-diego-ssh-host-key
  - rotate-router-secrets
  - rotate-cc-secrets
  - rotate-blobstore-secrets
  - rotate-dropsonde-secret
  - rotate-mysql-secrets
  - deploy-to-rotate-basics
- name: ca-certificates
  jobs: 
  - manual-rotate-cas
  - rotate-cas-p1
  - deploy-to-rotate-cas-p1
  - rotate-cas-p2
  - deploy-to-rotate-cas-p2
  - rotate-cas-p3
  - deploy-to-rotate-cas-p3
- name: consul-encrypt-keys
  jobs: 
  - manual-rotate-consul-keys
  - rotate-consul-p1
  - deploy-to-rotate-consul-p1
  - rotate-consul-p2
  - deploy-to-rotate-consul-p2
- name: jwt-keys
  jobs: 
  - manual-rotate-jwt-keys
  - rotate-jwt-keys-p1
  - deploy-to-rotate-jwt-p1
  - rotate-jwt-keys-p2
  - deploy-to-rotate-jwt-p2
- name: bbs-keys
  jobs: 
  - manual-rotate-bbs-keys
  - rotate-bbs-keys-p1
  - deploy-to-rotate-bbs-p1
  - rotate-bbs-keys-p2
  - deploy-to-rotate-bbs-p2
- name: database-users
  jobs: 
  - manual-rotate-db-users
  - rotate-db-users-p1
  - deploy-to-rotate-db
  - rotate-db-users-p2

resources: 
- name: manual-rotate-basics
  type: time
  source: 
    interval: 1m

- name: manual-rotate-cas
  type: time
  source: 
    interval: 1m

- name: manual-rotate-consul-keys
  type: time
  source: 
    interval: 1m

- name: manual-rotate-jwt-keys
  type: time
  source: 
    interval: 1m

- name: manual-rotate-bbs-keys
  type: time
  source: 
    interval: 1m

- name: manual-rotate-db-users
  type: time
  source: 
    interval: 1m

- name: alpha-rotato
  type: git
  source:
    uri: https://github.com/danjahner/alpha-rotato.git
    branch: master

jobs: 
- name: manual-rotate-basics
  plan: 
  - get: manual-rotate-basics
    trigger: false

- name: rotate-certificates
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-certificates-by-ca.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      SIGNED_BY_TO_ROTATE:
      - "uaa_ca"
      - "router_ca"
      - "loggregator_ca"
      - "consul_agent_ca"
      - "service_cf_internal_ca"
      - "network_policy_ca"
      - "silk_ca"

- name: rotate-uaa-client-secrets
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "uaa_clients_tcp_router_secret"
      - "uaa_clients_tcp_emitter_secret"
      - "uaa_clients_ssh-proxy_secret"
      - "uaa_clients_gorouter_secret"
      - "uaa_clients_doppler_secret"
      - "uaa_clients_cloud_controller_username_lookup_secret"
      - "uaa_clients_cc-service-dashboards_secret"
      - "uaa_clients_cc-routing_secret"
      - "uaa_clients_network_policy_secret"
      - "uaa_clients_cc_service_key_client_secret"
      - "uaa_clients_routing_api_client_secret"
      - "uaa_admin_client_secret"
      - "cf_admin_password"

- name: rotate-nats-password
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "nats_password"

- name: rotate-diego-ssh-host-key
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "diego_ssh_proxy_host_key"

- name: rotate-router-secrets
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "router_route_services_secret"
      - "router_status_password"

- name: rotate-cc-secrets
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "cc_bulk_api_password"
      - "cc_staging_upload_password"
      - "cc_internal_api_password"

- name: rotate-blobstore-secrets
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "blobstore_secure_link_secret"
      - "blobstore_admin_users_password"

- name: rotate-dropsonde-secret
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "dropsonde_shared_secret"

- name: rotate-mysql-secrets
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - manual-rotate-basics
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CREDS_TO_ROTATE:
      - "cf_mysql_mysql_admin_password"
      - "cf_mysql_mysql_cluster_health_password"
      - "cf_mysql_mysql_galera_healthcheck_endpoint_password"
      - "cf_mysql_mysql_galera_healthcheck_password"
      - "cf_mysql_proxy_api_password"

- name: deploy-to-rotate-basics
  plan: 
  - get: manual-rotate-basics
    trigger: true
    passed: 
    - rotate-certificates
    - rotate-uaa-client-secrets
    - rotate-nats-password
    - rotate-diego-ssh-host-key
    - rotate-router-secrets
    - rotate-cc-secrets
    - rotate-blobstore-secrets
    - rotate-dropsonde-secret
    - rotate-mysql-secrets
  - get: alpha-rotato
  - task: deploy-to-rotate-basics
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: manual-rotate-cas
  plan: 
  - get: manual-rotate-cas
    trigger: false

- name: rotate-cas-p1
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - manual-rotate-cas
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-cas-part1.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CAS_TO_ROTATE:
      - "uaa_ca"
      - "router_ca"
      - "loggregator_ca"
      - "consul_agent_ca"
      - "service_cf_internal_ca"
      - "network_policy_ca"
      - "silk_ca"

- name: deploy-to-rotate-cas-p1
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - rotate-cas-p1
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-cas-p2
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - deploy-to-rotate-cas-p1
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-certificates-by-ca.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      SIGNED_BY_TO_ROTATE:
      - "uaa_ca"
      - "router_ca"
      - "loggregator_ca"
      - "consul_agent_ca"
      - "service_cf_internal_ca"
      - "network_policy_ca"
      - "silk_ca"

- name: deploy-to-rotate-cas-p2
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - rotate-cas-p2
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-cas-p3
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - deploy-to-rotate-cas-p2
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-cas-part3.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      CAS_TO_ROTATE:
      - "uaa_ca"
      - "router_ca"
      - "loggregator_ca"
      - "consul_agent_ca"
      - "service_cf_internal_ca"
      - "network_policy_ca"
      - "silk_ca"

- name: deploy-to-rotate-cas-p3
  plan: 
  - get: manual-rotate-cas
    trigger: true
    passed: 
    - rotate-cas-p3
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: manual-rotate-consul-keys
  plan: 
  - get: manual-rotate-consul-keys
    trigger: false

- name: rotate-consul-p1
  plan: 
  - get: manual-rotate-consul-keys
    trigger: true
    passed: 
    - manual-rotate-consul-keys
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-consul-keys-part1.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "consul_encrypt_key"

- name: deploy-to-rotate-consul-p1
  plan: 
  - get: manual-rotate-consul-keys
    trigger: true
    passed: 
    - rotate-consul-p1
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-consul-p2
  plan: 
  - get: manual-rotate-consul-keys
    trigger: true
    passed: 
    - deploy-to-rotate-consul-p1
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-consul-keys-part2.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "consul_encrypt_key"

- name: deploy-to-rotate-consul-p2
  plan: 
  - get: manual-rotate-consul-keys
    trigger: true
    passed: 
    - rotate-consul-p2
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: manual-rotate-jwt-keys
  plan: 
  - get: manual-rotate-jwt-keys
    trigger: false

- name: rotate-jwt-keys-p1
  plan: 
  - get: manual-rotate-jwt-keys
    trigger: true
    passed: 
    - manual-rotate-jwt-keys
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-jwt-keys-part1.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "uaa_jwt_signing_key"

- name: deploy-to-rotate-jwt-p1
  plan: 
  - get: manual-rotate-jwt-keys
    trigger: true
    passed: 
    - rotate-jwt-keys-p1
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-jwt-keys-p2
  plan: 
  - get: manual-rotate-jwt-keys
    trigger: true
    passed: 
    - deploy-to-rotate-jwt-p1
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-jwt-keys-part2.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "uaa_jwt_signing_key"

- name: deploy-to-rotate-jwt-p2
  plan: 
  - get: manual-rotate-jwt-keys
    trigger: true
    passed: 
    - rotate-jwt-keys-p2
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: manual-rotate-bbs-keys
  plan: 
  - get: manual-rotate-bbs-keys
    trigger: false

- name: rotate-bbs-keys-p1
  plan: 
  - get: manual-rotate-bbs-keys
    trigger: true
    passed: 
    - manual-rotate-bbs-keys
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-bbs-keys-part1.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "diego_bbs_encryption_keys_passphrase"

- name: deploy-to-rotate-bbs-p1
  plan: 
  - get: manual-rotate-bbs-keys
    trigger: true
    passed: 
    - rotate-bbs-keys-p1
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-bbs-keys-p2
  plan: 
  - get: manual-rotate-bbs-keys
    trigger: true
    passed: 
    - deploy-to-rotate-bbs-p1
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-bbs-keys-part2.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      KEYS_TO_ROTATE:
      - "diego_bbs_encryption_keys_passphrase"

- name: deploy-to-rotate-bbs-p2
  plan: 
  - get: manual-rotate-bbs-keys
    trigger: true
    passed: 
    - rotate-bbs-keys-p2
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: manual-rotate-db-users
  plan: 
  - get: manual-rotate-db-users
    trigger: false

- name: rotate-db-users-p1
  plan: 
  - get: manual-rotate-db-users
    trigger: true
    passed: 
    - manual-rotate-db-users
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/generate-users.yml
    params:
      CREDHUB_SERVER: ((director_addr)):8844
      CREDHUB_CLIENT: ((director_client.username))
      CREDHUB_SECRET: ((director_client.password))
      CREDHUB_CA_CERT: ((director_ca.certificate))
      BOSH_NAME: ((director_name))
      BOSH_DEPLOYMENT: ((deployment_name))
      USERS_TO_GENERATE:
      - "cc_database"
      - "diego_database"
      - "network_connectivity_database"
      - "network_policy_database"
      - "routing_api_database"
      - "uaa_database"
      - "locket_database"

- name: deploy-to-rotate-db
  plan: 
  - get: manual-rotate-db-users
    trigger: true
    passed: 
    - rotate-db-users-p1
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/deploy.yml
    params: *deploy_config

- name: rotate-db-users-p2
  plan:
  - get: manual-rotate-db-users
    trigger: true
    passed:
    - deploy-to-rotate-db
  - get: alpha-rotato
  - task: revoke-old-mysql-users
    file: alpha-rotato/tasks/revoke-users.yml
    params:
      BOSH_ENVIRONMENT: ((director_addr))
      BOSH_DEPLOYMENT: ((deployment_name))
      BOSH_CA_CERT: ((director_ca.certificate))
      BOSH_CLIENT: ((director_client.username))
      BOSH_CLIENT_SECRET: ((director_client.password))
      BOSH_JUMPBOX_SSH_KEY: ((director_jumpbox.private_key))
      MYSQL_USERNAME: root
      MYSQL_PASSWORD_REF: "/((director_name))/((deployment_name))/cf_mysql_mysql_admin_password"
      BOSH_NAME: ((director_name))
      USERS_TO_REVOKE_PRIOR:
      - "cc_database"
      - "diego_database"
      - "network_connectivity_database"
      - "network_policy_database"
      - "routing_api_database"
      - "uaa_database"
      - "locket_database"

