resources: 
- name: manual-rotate
  type: time
  source: 
    interval: 1m

- name: daily-rotate
  type: time
  source: 
    interval: 24h

- name: alpha-rotato
  type: git
  source:
    uri: https://github.com/danjahner/alpha-rotato.git
    branch: master

jobs: 
- name: manual-rotate
  plan: 
  - get: manual-rotate
    trigger: false

- name: rotate-certificates
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-certificates-by-ca.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      SIGNED_BY_TO_ROTATE:
      - "/dan_director/cf-credhub/uaa_ca"
      - "/dan_director/cf-credhub/service_cf_internal_ca"
      - "/dan_director/cf-credhub/credhub_ca"
      - "/dan_director/cf-credhub/instance_identity_ca"
      - "/dan_director/cf-credhub/etcd_ca"
      - "/dan_director/cf-credhub/consul_agent_ca"
      - "/dan_director/cf-credhub/etcd_peer_ca"
      - "/dan_director/cf-credhub/loggregator_ca"
      - "/dan_director/cf-credhub/router_ca"
      - "/dan_director/cf-credhub/uaa_admin_client_secret"
      - "/dan_director/cf-credhub/uaa_scim_users_admin_password"

- name: rotate-uaa-client-secrets
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/uaa_clients_tcp_router_secret"
      - "/dan_director/cf-credhub/uaa_clients_tcp_emitter_secret"
      - "/dan_director/cf-credhub/uaa_clients_ssh-proxy_secret"
      - "/dan_director/cf-credhub/uaa_clients_gorouter_secret"
      - "/dan_director/cf-credhub/uaa_clients_doppler_secret"
      - "/dan_director/cf-credhub/uaa_clients_cloud_controller_username_lookup_secret"
      - "/dan_director/cf-credhub/uaa_clients_cc-service-dashboards_secret"
      - "/dan_director/cf-credhub/uaa_clients_cc-routing_secret"

- name: rotate-nats-password
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/nats_password"

- name: rotate-diego-ssh-host-key
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/diego_ssh_proxy_host_key"

- name: rotate-router-secrets
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/router_route_services_secret"
      - "/dan_director/cf-credhub/router_status_password"

- name: rotate-cc-secrets
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/cc_bulk_api_password"
      - "/dan_director/cf-credhub/cc_staging_upload_password"
      - "/dan_director/cf-credhub/cc_internal_api_password"

- name: rotate-blobstore-secrets
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/blobstore_secure_link_secret"
      - "/dan_director/cf-credhub/blobstore_admin_users_password"

- name: rotate-dropsonde-secret
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - manual-rotate
  - get: daily-rotate
    trigger: true
  - get: alpha-rotato
  - task: rotate-credential
    file: alpha-rotato/tasks/rotate-credentials.yml
    params:
      CREDHUB_SERVER: ((director-addr)):8844
      CREDHUB_CLIENT: ((dan_director_client.username))
      CREDHUB_SECRET: ((dan_director_client.password))
      CREDHUB_CA_CERT: ((dan_director_gcp_ca.certificate))
      CREDS_TO_ROTATE:
      - "/dan_director/cf-credhub/dropsonde_shared_secret"

- name: deploy-to-rotate
  plan: 
  - get: manual-rotate
    trigger: true
    passed: 
    - rotate-certificates
    - rotate-uaa-client-secrets
    - rotate-nats-password
    - rotate-diego-ssh-host-key
    - rotate-router-secrets
    - rotate-cc-secrets
    - rotate-blobstore-secrets
    - rotate-dropsonde-secret
  - get: daily-rotate
    trigger: true
    passed: 
    - rotate-certificates
    - rotate-uaa-client-secrets
    - rotate-nats-password
    - rotate-diego-ssh-host-key
    - rotate-router-secrets
    - rotate-cc-secrets
    - rotate-blobstore-secrets
    - rotate-dropsonde-secret
  - get: alpha-rotato
  - task: deploy-to-rotate
    file: alpha-rotato/tasks/rotate-deploy.yml
    params:
      BOSH_ENVIRONMENT: ((director-addr))
      BOSH_DEPLOYMENT: cf-credhub
      BOSH_CA_CERT: ((dan_director_gcp_ca.certificate))
      BOSH_CLIENT: ((dan_director_client.username))
      BOSH_CLIENT_SECRET: ((dan_director_client.password))

